name: PopupAlerts
main: PopupAlerts\PopupAlerts
version: 1.5
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: STARTUP
author: EvolSoft
description: Show alerts in popups
website: https://www.evolsoft.tk
